import random

QUOTES = [
    "The unexamined life is not worth living.",
    "We do not learn from experience... we learn from reflecting on experience.",
    "Happiness depends upon ourselves.",
    "Everything has beauty, but not everyone sees it.",
    "Life isn't about finding yourself. Life is about creating yourself.",
    "Your life does not get better by chance, it gets better by change.",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    "Do not go where the path may lead, go instead where there is no path and leave a trail.",
    "Turn your wounds into wisdom.",
    "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
    "It does not matter how slowly you go as long as you do not stop.",
    "In three words I can sum up everything I've learned about life: it goes on.",
    "Be yourself; everyone else is already taken.",
    "Life is really simple, but we insist on making it complicated.",
    "He who has a why to live can bear almost any how.",
    "The only journey is the one within.",
    "Don’t count the days, make the days count.",
    "Difficulties strengthen the mind, as labor does the body.",
    "The greatest wealth is to live content with little.",
    "Challenges are what make life interesting; overcoming them is what makes life meaningful.",
    "Act as if what you do makes a difference. It does.",
    "Happiness is not something ready made. It comes from your own actions.",
    "Do not let making a living prevent you from making a life.",
    "The more you praise and celebrate your life, the more there is in life to celebrate.",
    "Your time is limited, so don’t waste it living someone else’s life.",
    "Life is about making an impact, not making an income.",
    "Success is not how high you have climbed, but how you make a positive difference to the world.",
    "You only live once, but if you do it right, once is enough.",
    "Don’t wait. The time will never be just right.",
    "Life is 10% what happens to us and 90% how we react to it.",
    "It is never too late to be what you might have been.",
    "A man who dares to waste one hour of time has not discovered the value of life.",
    "Everything you’ve ever wanted is on the other side of fear.",
    "Life is short, and it is up to you to make it sweet.",
    "In the end, it’s not the years in your life that count. It’s the life in your years.",
    "Do what you can, with what you have, where you are.",
    "Keep your eyes on the stars, and your feet on the ground.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "Life isn’t about waiting for the storm to pass, it’s about learning to dance in the rain.",
    "Life is either a daring adventure or nothing at all.",
    "Not how long, but how well you have lived is the main thing.",
    "The purpose of life is a life of purpose.",
    "Don’t cry because it’s over, smile because it happened.",
    "The best way to prepare for life is to begin to live.",
    "It always seems impossible until it’s done.",
    "You have within you right now, everything you need to deal with whatever the world can throw at you.",
    "Be not afraid of life. Believe that life is worth living, and your belief will help create the fact.",
    "Do not go where the path may lead, go instead where there is no path and leave a trail.",
    "Happiness is not something you postpone for the future; it is something you design for the present.",
    "Life is about the journey, not the destination."
]

def get_quote() -> str:
    return random.choice(QUOTES)